### ISSUE TITLE
Info on how to setup ss on openwrt

### ISSUE THREAD

**Issue by Docop2** [pexcn/openwrt-transproxy#2]
Hi So i.ve tried with the official shadowsock package for owrt and see yours. While i,m not sure on how to install your.. do you have an example of a working setup ? I do have a server, i can connect with pretty much all , but openwrt, i have no clue how to config it .. or just put the server in sss0 and do a sstun or ssredir.. ? 
thanks in advance for some hints

**Comment by pexcn** [comment]
No, this project not work now.

**Comment by pexcn** [comment]
Look here: https://github.com/pexcn/transproxy
It should work now, you can simply use it, although the help info is not complete, like this:
```sh
transproxy -s <proxy_server_ip> -p <tproxy_tcp_port> -P <tproxy_udp_port> --dst-direct </path/to/direct1.txt>,</path/to/direct2.txt> --self-proxy
```
